name = "LowRankEnKFGridVortex"
uuid = "076f3ad3-be15-474f-9d1d-94375701e936"
authors = ["Hanieh Mousavi"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
